name: skype
description: chat application with calling

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:

 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter

dev_dependencies:
  cloud_firestore: ^4.4.4
  dartz: ^0.10.1
  firebase_auth: ^4.2.10
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.1
  google_sign_in: ^6.0.2
  shimmer: ^2.0.0

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
