name: skype
description: chat application with calling

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_http_formatter: ^2.1.1
  emoji_picker_flutter: null
  equatable: ^2.0.5

  file_picker: ^5.2.6
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

  flutter_secure_storage: ^8.0.0
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.7
  intl: null
  path: null
  path_provider: null
  permission_handler: ^10.2.0
  regexpattern: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.20

  chewie: ^1.4.0
  video_player: ^2.6.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
